# Generated by Django 6.0.4 on 2026-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoice_due_amount_alter_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], default='Cash', max_length=30),
        ),
    ]
