# Generated by Django 6.0.4 on 2026-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invoice_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='frame_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='frame_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='frame_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='glass_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='glass_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='glass_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='lens_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
