# Generated by Django 6.0.4 on 2026-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_frame_price_invoice_frame_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='frame_type',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Three-pic', 'Three-pic'), ('Carbon', 'Carbon'), ('Supra', 'Supra'), ('Goggle', 'Goggle'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
