# Generated by Django 6.0.4 on 2026-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_invoice_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='frame_type',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Three-pic', 'Three-pic'), ('Carbon', 'Carbon'), ('Supra', 'Supra'), ('Goggle', 'Goggle'), ('Others', 'Others')], default='Metal', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='glass_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
