# Generated by Django 6.0.4 on 2026-05-16 11:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_invoice_frame_type_alter_invoice_glass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='frame_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='frame_type',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Three-pic', 'Three-pic'), ('Carbon', 'Carbon'), ('Supra', 'Supra'), ('Goggle', 'Goggle'), ('Others', 'Others'), ('Not Required', 'Not Required')], default='Not Required', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='glass_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='glass_type',
            field=models.CharField(blank=True, default='Not Required', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lens_type',
            field=models.CharField(blank=True, default='Not Required', max_length=200, null=True),
        ),
    ]
